# Generated by Django 2.2.6 on 2019-10-23 17:56

from django.db import migrations
from  src.models.user import Seat
import  json
def my_function(apps, schema_editor):
    data = []
    print(11111111111111111)
    with open('src/fakerdata/seat.json') as f:

        seats = json.load(f)
        for item in seats:
            seat = Seat(name=str(item['name']))
            data.append(seat)
        Seat.objects.bulk_create(data)


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20191024_0008'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]
