# Generated by Django 2.2.6 on 2019-10-24 02:18

from django.db import migrations

from  src.models.user import Room
import  json
def my_function(apps, schema_editor):
    data = []
    print(11111111111111111)
    with open('src/fakerdata/room.json') as f:

        seats = json.load(f)
        for item in seats:
            seat = Room(name=str(item['name']),location=item['location'],max_student=item['max_student'])
            data.append(seat)
        Room.objects.bulk_create(data)

class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20191024_0903'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]
