# Generated by Django 2.2.6 on 2019-10-24 02:34

from django.db import migrations
from  src.models.user import Exam
import  json
def my_function(apps, schema_editor):


            seat = Exam(name='ABC',status=True)
            seat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20191024_0918'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]
