# Generated by Django 2.2.6 on 2019-10-24 02:47

from django.db import migrations
from  src.models.user import RoomSeat,Room,Seat
import  json
def my_function(apps, schema_editor):


            for x in range(98):
                for y in range(48):
                    a =RoomSeat(room_id=Room.objects.get(name=y+1),seat_id=Seat.objects.get(name=str(x+2)))
                    print(x,y)
                    a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20191024_0934'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]
