# Generated by Django 2.2.6 on 2019-10-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('location', models.TextField()),
                ('max_student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=200)),
                ('full_name', models.TextField()),
                ('role', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.User')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRoomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Room')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('be_registered', models.BooleanField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Exam')),
                ('rom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Room')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.User')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Exam')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Subject')),
            ],
        ),
    ]
