# Generated by Django 2.2.6 on 2019-11-01 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('location', models.TextField()),
                ('max_student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('full_name', models.TextField()),
                ('role', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Room')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Seat')),
            ],
            options={
                'unique_together': {('room_id', 'seat_id')},
            },
        ),
        migrations.CreateModel(
            name='ExamUserSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('be_register', models.BooleanField(default=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Exam')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.User')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoomSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('no_of_student', models.IntegerField(default=0)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Exam')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Room')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='src.ExamRoomSubject')),
                ('seat_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.RoomSeat')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='src.User')),
            ],
            options={
                'unique_together': {('user', 'schedule')},
            },
        ),
    ]
