# Generated by Django 2.2.6 on 2019-10-17 15:52


from django.db import migrations
from  src.models.user import User
from  django.contrib.auth.hashers import SHA1PasswordHasher

def my_function(apps, schema_editor):


    a= User(username="17020706",password=SHA1PasswordHasher().encode("123456789",salt='1123'),role=1)
    b= User( username = "10020706",password=SHA1PasswordHasher().encode("123456789",salt='1123'),role=2)

    User.objects.bulk_create([a,b])



class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]
