# Generated by Django 2.2.6 on 2019-11-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20191024_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examusersubject',
            unique_together={('subject_id', 'user_id', 'exam_id')},
        ),
    ]
