# Generated by Django 2.2.6 on 2019-10-24 02:18

from django.db import migrations

from  src.models.user import Room,RoomSeat,Seat
import  json
def my_function(apps, schema_editor):

    data = []
    with open('src/fakerdata/seat.json') as f:

        seats = json.load(f)
        for item in seats:
            seat = Seat(name=str(item['name']))
            data.append(seat)
        Seat.objects.bulk_create(data)
    for x in range(5):
        for y in range(48):

            a = RoomSeat(room_id=Room.objects.get(id=x+ 1), seat_id=Seat.objects.get(name=str(y + 2)))
            print(x, y)
            a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20191024_0918'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]
